project_id = "mcnzcagvdcoutqdfceai"

[functions.import-safarine-tours]
verify_jwt = false

[functions.import-safarine]
verify_jwt = false

[functions.optimize-images]
verify_jwt = false

[functions.csv-import-images]
verify_jwt = false

[functions.b2b-secure-register]
verify_jwt = false
