-- Add missing translation keys for navigation, homepage, admin wizard, and other components

-- Navigation translations
INSERT INTO translations (key_name, value, locale, category, is_active) VALUES
('nav.home', 'Home', 'en', 'navigation', true),
('nav.home', 'Accueil', 'fr', 'navigation', true),
('nav.tours', 'Tours', 'en', 'navigation', true),
('nav.tours', 'Circuits', 'fr', 'navigation', true),
('nav.about', 'About', 'en', 'navigation', true),
('nav.about', 'À propos', 'fr', 'navigation', true),
('nav.contact', 'Contact', 'en', 'navigation', true),
('nav.contact', 'Contact', 'fr', 'navigation', true),
('nav.pro', 'Pro', 'en', 'navigation', true),
('nav.pro', 'Pro', 'fr', 'navigation', true),

-- Homepage hero section
('hero.title', 'Discover Thailand Like Never Before', 'en', 'homepage', true),
('hero.title', 'Découvrez la Thaïlande comme jamais auparavant', 'fr', 'homepage', true),
('hero.subtitle', 'Authentic experiences, local guides, unforgettable memories', 'en', 'homepage', true),
('hero.subtitle', 'Expériences authentiques, guides locaux, souvenirs inoubliables', 'fr', 'homepage', true),
('hero.cta', 'Explore Tours', 'en', 'homepage', true),
('hero.cta', 'Explorer les circuits', 'fr', 'homepage', true),

-- Why Safarine section
('whySafarine.title', 'Why Choose Safarine?', 'en', 'homepage', true),
('whySafarine.title', 'Pourquoi choisir Safarine ?', 'fr', 'homepage', true),
('whySafarine.features.authentic', 'Authentic local experiences', 'en', 'homepage', true),
('whySafarine.features.authentic', 'Expériences locales authentiques', 'fr', 'homepage', true),
('whySafarine.features.respect', 'Respectful and sustainable tourism', 'en', 'homepage', true),
('whySafarine.features.respect', 'Tourisme respectueux et durable', 'fr', 'homepage', true),
('whySafarine.features.offBeaten', 'Off the beaten path adventures', 'en', 'homepage', true),
('whySafarine.features.offBeaten', 'Aventures hors des sentiers battus', 'fr', 'homepage', true),
('whySafarine.features.guides', 'Expert local guides', 'en', 'homepage', true),
('whySafarine.features.guides', 'Guides locaux experts', 'fr', 'homepage', true),
('whySafarine.description', 'We create unique travel experiences that connect you with the real Thailand, its people, and its culture.', 'en', 'homepage', true),
('whySafarine.description', 'Nous créons des expériences de voyage uniques qui vous connectent à la vraie Thaïlande, ses habitants et sa culture.', 'fr', 'homepage', true),
('whySafarine.image.alt', 'Why choose Safarine for your Thailand adventure', 'en', 'homepage', true),
('whySafarine.image.alt', 'Pourquoi choisir Safarine pour votre aventure en Thaïlande', 'fr', 'homepage', true),

-- Pro CTA section
('pro.cta.title', 'Ready to Partner with Safarine?', 'en', 'homepage', true),
('pro.cta.title', 'Prêt à vous associer avec Safarine ?', 'fr', 'homepage', true),
('pro.cta.signup', 'Sign Up as Partner', 'en', 'homepage', true),
('pro.cta.signup', 'S''inscrire comme partenaire', 'fr', 'homepage', true),
('pro.cta.login', 'Partner Login', 'en', 'homepage', true),
('pro.cta.login', 'Connexion partenaire', 'fr', 'homepage', true),

-- Admin wizard main
('admin.wizard.title', 'Create New Tour', 'en', 'admin', true),
('admin.wizard.title', 'Créer un nouveau circuit', 'fr', 'admin', true),
('admin.wizard.steps.basic.title', 'Basic Information', 'en', 'admin', true),
('admin.wizard.steps.basic.title', 'Informations de base', 'fr', 'admin', true),
('admin.wizard.steps.basic.description', 'Set up the basic details of your tour', 'en', 'admin', true),
('admin.wizard.steps.basic.description', 'Configurez les détails de base de votre circuit', 'fr', 'admin', true),
('admin.wizard.steps.itinerary.title', 'Itinerary', 'en', 'admin', true),
('admin.wizard.steps.itinerary.title', 'Itinéraire', 'fr', 'admin', true),
('admin.wizard.steps.itinerary.description', 'Plan your tour itinerary', 'en', 'admin', true),
('admin.wizard.steps.itinerary.description', 'Planifiez l''itinéraire de votre circuit', 'fr', 'admin', true),
('admin.wizard.steps.highlights.title', 'Highlights', 'en', 'admin', true),
('admin.wizard.steps.highlights.title', 'Points forts', 'fr', 'admin', true),
('admin.wizard.steps.highlights.description', 'Add the main attractions and highlights', 'en', 'admin', true),
('admin.wizard.steps.highlights.description', 'Ajoutez les principales attractions et points forts', 'fr', 'admin', true),
('admin.wizard.steps.inclusions.title', 'Inclusions', 'en', 'admin', true),
('admin.wizard.steps.inclusions.title', 'Inclus', 'fr', 'admin', true),
('admin.wizard.steps.inclusions.description', 'Specify what is included and excluded', 'en', 'admin', true),
('admin.wizard.steps.inclusions.description', 'Spécifiez ce qui est inclus et exclu', 'fr', 'admin', true),
('admin.wizard.steps.images.title', 'Images', 'en', 'admin', true),
('admin.wizard.steps.images.title', 'Images', 'fr', 'admin', true),
('admin.wizard.steps.images.description', 'Upload and manage tour images', 'en', 'admin', true),
('admin.wizard.steps.images.description', 'Téléchargez et gérez les images du circuit', 'fr', 'admin', true),

-- Admin wizard navigation
('admin.wizard.navigation.back', 'Back', 'en', 'admin', true),
('admin.wizard.navigation.back', 'Retour', 'fr', 'admin', true),
('admin.wizard.navigation.next', 'Next', 'en', 'admin', true),
('admin.wizard.navigation.next', 'Suivant', 'fr', 'admin', true),
('admin.wizard.navigation.saveDraft', 'Save Draft', 'en', 'admin', true),
('admin.wizard.navigation.saveDraft', 'Sauvegarder le brouillon', 'fr', 'admin', true),
('admin.wizard.navigation.createTour', 'Create Tour', 'en', 'admin', true),
('admin.wizard.navigation.createTour', 'Créer le circuit', 'fr', 'admin', true),
('admin.wizard.progress.step', 'Step', 'en', 'admin', true),
('admin.wizard.progress.step', 'Étape', 'fr', 'admin', true),
('admin.wizard.progress.of', 'of', 'en', 'admin', true),
('admin.wizard.progress.of', 'sur', 'fr', 'admin', true),

-- Admin highlights section
('admin.highlights.title', 'Tour Highlights', 'en', 'admin', true),
('admin.highlights.title', 'Points forts du circuit', 'fr', 'admin', true),
('admin.highlights.description', 'Add the key highlights and attractions of your tour in both languages.', 'en', 'admin', true),
('admin.highlights.description', 'Ajoutez les points forts et attractions clés de votre circuit dans les deux langues.', 'fr', 'admin', true),
('admin.highlights.add', 'Add Highlight', 'en', 'admin', true),
('admin.highlights.add', 'Ajouter un point fort', 'fr', 'admin', true),
('admin.highlights.tips.title', 'Tips for effective highlights:', 'en', 'admin', true),
('admin.highlights.tips.title', 'Conseils pour des points forts efficaces :', 'fr', 'admin', true),
('admin.highlights.tips.specific', 'Be specific about what makes each highlight unique', 'en', 'admin', true),
('admin.highlights.tips.specific', 'Soyez spécifique sur ce qui rend chaque point fort unique', 'fr', 'admin', true),
('admin.highlights.tips.benefit', 'Focus on the benefit or experience for the traveler', 'en', 'admin', true),
('admin.highlights.tips.benefit', 'Concentrez-vous sur le bénéfice ou l''expérience pour le voyageur', 'fr', 'admin', true),
('admin.highlights.tips.emotional', 'Use emotional language that inspires excitement', 'en', 'admin', true),
('admin.highlights.tips.emotional', 'Utilisez un langage émotionnel qui inspire l''enthousiasme', 'fr', 'admin', true),
('admin.highlights.form.title.label', 'Title', 'en', 'admin', true),
('admin.highlights.form.title.label', 'Titre', 'fr', 'admin', true),
('admin.highlights.form.title.placeholder', 'Enter highlight title', 'en', 'admin', true),
('admin.highlights.form.title.placeholder', 'Saisissez le titre du point fort', 'fr', 'admin', true),
('admin.highlights.form.description.label', 'Description', 'en', 'admin', true),
('admin.highlights.form.description.label', 'Description', 'fr', 'admin', true),
('admin.highlights.form.description.placeholder', 'Describe this highlight in detail', 'en', 'admin', true),
('admin.highlights.form.description.placeholder', 'Décrivez ce point fort en détail', 'fr', 'admin', true),
('admin.highlights.none.title', 'No highlights added yet', 'en', 'admin', true),
('admin.highlights.none.title', 'Aucun point fort ajouté', 'fr', 'admin', true),
('admin.highlights.none.description', 'Click "Add Highlight" to create your first tour highlight.', 'en', 'admin', true),
('admin.highlights.none.description', 'Cliquez sur "Ajouter un point fort" pour créer votre premier point fort de circuit.', 'fr', 'admin', true),

-- Admin basic info form fields
('admin.basicInfo.title', 'Basic Tour Information', 'en', 'admin', true),
('admin.basicInfo.title', 'Informations de base du circuit', 'fr', 'admin', true),
('admin.basicInfo.description', 'Enter the essential details for your tour in both languages.', 'en', 'admin', true),
('admin.basicInfo.description', 'Saisissez les détails essentiels de votre circuit dans les deux langues.', 'fr', 'admin', true),
('admin.basicInfo.form.titles.label', 'Tour Titles', 'en', 'admin', true),
('admin.basicInfo.form.titles.label', 'Titres du circuit', 'fr', 'admin', true),
('admin.basicInfo.form.title.english.label', 'English Title', 'en', 'admin', true),
('admin.basicInfo.form.title.english.label', 'Titre anglais', 'fr', 'admin', true),
('admin.basicInfo.form.title.english.placeholder', 'Enter tour title in English', 'en', 'admin', true),
('admin.basicInfo.form.title.english.placeholder', 'Saisissez le titre du circuit en anglais', 'fr', 'admin', true),
('admin.basicInfo.form.title.french.label', 'French Title', 'en', 'admin', true),
('admin.basicInfo.form.title.french.label', 'Titre français', 'fr', 'admin', true),
('admin.basicInfo.form.title.french.placeholder', 'Enter tour title in French', 'en', 'admin', true),
('admin.basicInfo.form.title.french.placeholder', 'Saisissez le titre du circuit en français', 'fr', 'admin', true),
('admin.basicInfo.form.location.label', 'Location & Duration', 'en', 'admin', true),
('admin.basicInfo.form.location.label', 'Lieu et durée', 'fr', 'admin', true),
('admin.basicInfo.form.destination.label', 'Destination', 'en', 'admin', true),
('admin.basicInfo.form.destination.label', 'Destination', 'fr', 'admin', true),
('admin.basicInfo.form.destination.placeholder', 'Select destination', 'en', 'admin', true),
('admin.basicInfo.form.destination.placeholder', 'Sélectionnez la destination', 'fr', 'admin', true),
('admin.basicInfo.form.duration.days.label', 'Days', 'en', 'admin', true),
('admin.basicInfo.form.duration.days.label', 'Jours', 'fr', 'admin', true),
('admin.basicInfo.form.duration.nights.label', 'Nights', 'en', 'admin', true),
('admin.basicInfo.form.duration.nights.label', 'Nuits', 'fr', 'admin', true),
('admin.basicInfo.form.pricing.label', 'Pricing', 'en', 'admin', true),
('admin.basicInfo.form.pricing.label', 'Tarification', 'fr', 'admin', true),
('admin.basicInfo.form.price.label', 'Price (THB)', 'en', 'admin', true),
('admin.basicInfo.form.price.label', 'Prix (THB)', 'fr', 'admin', true),
('admin.basicInfo.form.price.placeholder', 'Enter price in Thai Baht', 'en', 'admin', true),
('admin.basicInfo.form.price.placeholder', 'Saisissez le prix en Baht thaï', 'fr', 'admin', true),
('admin.basicInfo.form.settings.label', 'Tour Settings', 'en', 'admin', true),
('admin.basicInfo.form.settings.label', 'Paramètres du circuit', 'fr', 'admin', true),
('admin.basicInfo.form.difficulty.label', 'Difficulty Level', 'en', 'admin', true),
('admin.basicInfo.form.difficulty.label', 'Niveau de difficulté', 'fr', 'admin', true),
('admin.basicInfo.form.difficulty.placeholder', 'Select difficulty', 'en', 'admin', true),
('admin.basicInfo.form.difficulty.placeholder', 'Sélectionnez la difficulté', 'fr', 'admin', true),
('admin.basicInfo.form.groupSize.min.label', 'Min Group Size', 'en', 'admin', true),
('admin.basicInfo.form.groupSize.min.label', 'Taille min du groupe', 'fr', 'admin', true),
('admin.basicInfo.form.groupSize.max.label', 'Max Group Size', 'en', 'admin', true),
('admin.basicInfo.form.groupSize.max.label', 'Taille max du groupe', 'fr', 'admin', true),
('admin.basicInfo.form.languages.label', 'Supported Languages', 'en', 'admin', true),
('admin.basicInfo.form.languages.label', 'Langues supportées', 'fr', 'admin', true),
('admin.basicInfo.form.descriptions.label', 'Tour Descriptions', 'en', 'admin', true),
('admin.basicInfo.form.descriptions.label', 'Descriptions du circuit', 'fr', 'admin', true),
('admin.basicInfo.form.description.english.label', 'English Description', 'en', 'admin', true),
('admin.basicInfo.form.description.english.label', 'Description anglaise', 'fr', 'admin', true),
('admin.basicInfo.form.description.english.placeholder', 'Describe your tour in English', 'en', 'admin', true),
('admin.basicInfo.form.description.english.placeholder', 'Décrivez votre circuit en anglais', 'fr', 'admin', true),
('admin.basicInfo.form.description.french.label', 'French Description', 'en', 'admin', true),
('admin.basicInfo.form.description.french.label', 'Description française', 'fr', 'admin', true),
('admin.basicInfo.form.description.french.placeholder', 'Describe your tour in French', 'en', 'admin', true),
('admin.basicInfo.form.description.french.placeholder', 'Décrivez votre circuit en français', 'fr', 'admin', true),

-- Difficulty levels
('difficulty.easy', 'Easy', 'en', 'admin', true),
('difficulty.easy', 'Facile', 'fr', 'admin', true),
('difficulty.moderate', 'Moderate', 'en', 'admin', true),
('difficulty.moderate', 'Modéré', 'fr', 'admin', true),
('difficulty.challenging', 'Challenging', 'en', 'admin', true),
('difficulty.challenging', 'Difficile', 'fr', 'admin', true),

-- Language options
('language.english', 'English', 'en', 'admin', true),
('language.english', 'Anglais', 'fr', 'admin', true),
('language.french', 'French', 'en', 'admin', true),
('language.french', 'Français', 'fr', 'admin', true),
('language.thai', 'Thai', 'en', 'admin', true),
('language.thai', 'Thaï', 'fr', 'admin', true),
('language.german', 'German', 'en', 'admin', true),
('language.german', 'Allemand', 'fr', 'admin', true),
('language.spanish', 'Spanish', 'en', 'admin', true),
('language.spanish', 'Espagnol', 'fr', 'admin', true);

-- Update updated_at timestamp for all translations
UPDATE translations SET updated_at = now() WHERE created_at = now();