-- Add comprehensive translation keys for ToursList, TourDetail, and SearchBar components

INSERT INTO translations (key_name, locale, value, category, is_active) VALUES
-- ToursList component translations
('tours.list.title', 'fr', 'Circuits & Activités en Thaïlande | Safarine Tours', 'page', true),
('tours.list.title', 'en', 'Tours & Activities in Thailand | Safarine Tours', 'page', true),
('tours.list.meta.description', 'fr', 'Découvrez nos circuits privés et activités en Thaïlande. Filtrez par destination, durée et mots-clés.', 'page', true),
('tours.list.meta.description', 'en', 'Discover our private tours and activities in Thailand. Filter by destination, duration and keywords.', 'page', true),
('tours.list.header.title', 'fr', 'Nos circuits et activités', 'page', true),
('tours.list.header.title', 'en', 'Our tours and activities', 'page', true),
('tours.list.header.subtitle', 'fr', 'Trek, culture et immersion loin du tourisme de masse.', 'page', true),
('tours.list.header.subtitle', 'en', 'Trekking, culture and immersion away from mass tourism.', 'page', true),
('tours.list.filters.aria', 'fr', 'Filtres', 'ui', true),
('tours.list.filters.aria', 'en', 'Filters', 'ui', true),
('tours.list.filters.category.placeholder', 'fr', 'Catégorie', 'ui', true),
('tours.list.filters.category.placeholder', 'en', 'Category', 'ui', true),
('tours.list.filters.category.all', 'fr', 'Toutes les catégories', 'ui', true),
('tours.list.filters.category.all', 'en', 'All categories', 'ui', true),
('tours.list.filters.category.unnamed', 'fr', 'Catégorie sans nom', 'ui', true),
('tours.list.filters.category.unnamed', 'en', 'Unnamed category', 'ui', true),
('tours.list.filters.duration.placeholder', 'fr', 'Durée', 'ui', true),
('tours.list.filters.duration.placeholder', 'en', 'Duration', 'ui', true),
('tours.list.filters.duration.all', 'fr', 'Toute durée', 'ui', true),
('tours.list.filters.duration.all', 'en', 'Any duration', 'ui', true),
('tours.list.filters.duration.half', 'fr', 'Moins d''une journée', 'ui', true),
('tours.list.filters.duration.half', 'en', 'Less than a day', 'ui', true),
('tours.list.filters.duration.one', 'fr', '1 jour', 'ui', true),
('tours.list.filters.duration.one', 'en', '1 day', 'ui', true),
('tours.list.filters.duration.multi', 'fr', '2+ jours', 'ui', true),
('tours.list.filters.duration.multi', 'en', '2+ days', 'ui', true),
('tours.list.search.placeholder', 'fr', 'Rechercher par titre, destination...', 'ui', true),
('tours.list.search.placeholder', 'en', 'Search by title, destination...', 'ui', true),
('tours.list.search.aria', 'fr', 'Recherche', 'ui', true),
('tours.list.search.aria', 'en', 'Search', 'ui', true),
('tours.list.results.aria', 'fr', 'Résultats', 'ui', true),
('tours.list.results.aria', 'en', 'Results', 'ui', true),
('tours.list.error', 'fr', 'Erreur lors du chargement des circuits', 'error', true),
('tours.list.error', 'en', 'Error loading tours', 'error', true),
('tours.list.no.results', 'fr', 'Aucun circuit trouvé pour ces critères', 'ui', true),
('tours.list.no.results', 'en', 'No tours found for these criteria', 'ui', true),
('tours.list.view.aria', 'fr', 'Voir {title}', 'ui', true),
('tours.list.view.aria', 'en', 'View {title}', 'ui', true),

-- TourDetail component translations
('tours.detail.loading', 'fr', 'Chargement du tour...', 'ui', true),
('tours.detail.loading', 'en', 'Loading tour...', 'ui', true),
('tours.detail.not.found.title', 'fr', 'Tour introuvable', 'error', true),
('tours.detail.not.found.title', 'en', 'Tour not found', 'error', true),
('tours.detail.not.found.message', 'fr', 'Désolé, nous n''avons pas trouvé le tour "{slug}". Il a peut-être été déplacé ou n''existe plus.', 'error', true),
('tours.detail.not.found.message', 'en', 'Sorry, we couldn''t find the tour "{slug}". It may have been moved or no longer exists.', 'error', true),
('tours.detail.not.found.all.tours', 'fr', 'Voir tous les tours', 'ui', true),
('tours.detail.not.found.all.tours', 'en', 'View all tours', 'ui', true),
('tours.detail.not.found.home', 'fr', 'Retour à l''accueil', 'ui', true),
('tours.detail.not.found.home', 'en', 'Back to home', 'ui', true),
('tours.detail.cta.contact', 'fr', 'Je contacte un vendeur Safarine', 'ui', true),
('tours.detail.cta.contact', 'en', 'I contact a Safarine salesperson', 'ui', true),
('tours.detail.cta.book', 'fr', 'Je réserve ce voyage !', 'ui', true),
('tours.detail.cta.book', 'en', 'I book this trip!', 'ui', true),
('tours.detail.info.title', 'fr', 'Infos et prix', 'ui', true),
('tours.detail.info.title', 'en', 'Info and prices', 'ui', true),
('tours.detail.duration.price.title', 'fr', 'Durée & Prix', 'ui', true),
('tours.detail.duration.price.title', 'en', 'Duration & Price', 'ui', true),
('tours.detail.duration.label', 'fr', 'Durée', 'ui', true),
('tours.detail.duration.label', 'en', 'Duration', 'ui', true),
('tours.detail.price.label', 'fr', 'Prix par adulte', 'ui', true),
('tours.detail.price.label', 'en', 'Price per adult', 'ui', true),
('tours.detail.included.title', 'fr', 'Ce prix inclut', 'ui', true),
('tours.detail.included.title', 'en', 'This price includes', 'ui', true),
('tours.detail.excluded.title', 'fr', 'Ce prix n''inclut pas', 'ui', true),
('tours.detail.excluded.title', 'en', 'This price does not include', 'ui', true),
('tours.detail.pricing.note', 'fr', 'Tarifs indicatifs, susceptibles d''évoluer selon la saison et la disponibilité.', 'ui', true),
('tours.detail.pricing.note', 'en', 'Indicative prices, subject to change according to season and availability.', 'ui', true),
('tours.detail.another.search', 'fr', 'Une autre recherche ?', 'ui', true),
('tours.detail.another.search', 'en', 'Another search?', 'ui', true),
('tours.detail.suggestions.title', 'fr', 'Nos suggestions', 'ui', true),
('tours.detail.suggestions.title', 'en', 'Our suggestions', 'ui', true),

-- Default included/excluded items
('tours.detail.included.default.guide', 'fr', 'Guide local francophone', 'content', true),
('tours.detail.included.default.guide', 'en', 'French-speaking local guide', 'content', true),
('tours.detail.included.default.transfers', 'fr', 'Transferts mentionnés', 'content', true),
('tours.detail.included.default.transfers', 'en', 'Mentioned transfers', 'content', true),
('tours.detail.included.default.activities', 'fr', 'Activités prévues', 'content', true),
('tours.detail.included.default.activities', 'en', 'Planned activities', 'content', true),
('tours.detail.excluded.default.flights', 'fr', 'Vols internationaux', 'content', true),
('tours.detail.excluded.default.flights', 'en', 'International flights', 'content', true),
('tours.detail.excluded.default.insurance', 'fr', 'Assurances', 'content', true),
('tours.detail.excluded.default.insurance', 'en', 'Insurance', 'content', true),
('tours.detail.excluded.default.personal', 'fr', 'Dépenses personnelles', 'content', true),
('tours.detail.excluded.default.personal', 'en', 'Personal expenses', 'content', true),

-- SearchBar option values (currently hardcoded)
('search.destinations.kanchanaburi', 'fr', 'Kanchanaburi', 'ui', true),
('search.destinations.kanchanaburi', 'en', 'Kanchanaburi', 'ui', true),
('search.destinations.chiangmai', 'fr', 'Chiang Mai', 'ui', true),
('search.destinations.chiangmai', 'en', 'Chiang Mai', 'ui', true),
('search.destinations.isaan', 'fr', 'Nord-Est Thaïlande', 'ui', true),
('search.destinations.isaan', 'en', 'Northeast Thailand', 'ui', true),
('search.activities.escooter', 'fr', 'E-scooter', 'ui', true),
('search.activities.escooter', 'en', 'E-scooter', 'ui', true),
('search.activities.river', 'fr', 'Rivière', 'ui', true),
('search.activities.river', 'en', 'River', 'ui', true),
('search.activities.kayak', 'fr', 'Kayak', 'ui', true),
('search.activities.kayak', 'en', 'Kayak', 'ui', true),
('search.durations.halfday', 'fr', '1/2', 'ui', true),
('search.durations.halfday', 'en', '1/2', 'ui', true),
('search.durations.oneday', 'fr', '1', 'ui', true),
('search.durations.oneday', 'en', '1', 'ui', true),
('search.durations.multiday', 'fr', '2+', 'ui', true),
('search.durations.multiday', 'en', '2+', 'ui', true);