-- Add user authentication translation keys (excluding already existing ones)
INSERT INTO translations (locale, key_name, value, category, namespace, description) VALUES
-- English translations (excluding common.loading and common.backToHome which may exist)
('en', 'auth.title', 'Authentication', 'user_auth', 'main', 'Main auth page title'),
('en', 'auth.welcome', 'Welcome to Safarine', 'user_auth', 'main', 'Auth welcome message'),
('en', 'auth.subtitle', 'Sign in to access your account and bookings', 'user_auth', 'main', 'Auth subtitle'),
('en', 'auth.email', 'Email', 'user_auth', 'main', 'Email field label'),
('en', 'auth.password', 'Password', 'user_auth', 'main', 'Password field label'),
('en', 'auth.confirmPassword', 'Confirm Password', 'user_auth', 'main', 'Confirm password field label'),
('en', 'auth.login.title', 'Sign In', 'user_auth', 'main', 'Login tab title'),
('en', 'auth.login.submit', 'Sign In', 'user_auth', 'main', 'Login submit button'),
('en', 'auth.login.success', 'Successfully signed in!', 'user_auth', 'main', 'Login success message'),
('en', 'auth.login.error', 'Invalid email or password', 'user_auth', 'main', 'Login error message'),
('en', 'auth.register.title', 'Sign Up', 'user_auth', 'main', 'Register tab title'),
('en', 'auth.register.submit', 'Create Account', 'user_auth', 'main', 'Register submit button'),
('en', 'auth.register.success', 'Account created! Please check your email to confirm your account.', 'user_auth', 'main', 'Register success message'),
('en', 'auth.register.error', 'Failed to create account', 'user_auth', 'main', 'Register error message'),
('en', 'auth.register.passwordMismatch', 'Passwords do not match', 'user_auth', 'main', 'Password mismatch error'),
('en', 'auth.signOut', 'Sign Out', 'user_auth', 'main', 'Sign out button'),
('en', 'auth.meta.description', 'Sign in or create an account to access your Safarine Tours bookings and profile', 'user_auth', 'main', 'Auth page meta description'),
('en', 'profile.title', 'My Profile', 'user_auth', 'main', 'Profile page title'),
('en', 'profile.memberSince', 'Member Since', 'user_auth', 'main', 'Member since label'),
('en', 'profile.meta.description', 'Manage your Safarine Tours profile and account settings', 'user_auth', 'main', 'Profile page meta description'),
('en', 'menu.account', 'My Account', 'user_auth', 'main', 'Account menu item'),

-- French translations
('fr', 'auth.title', 'Authentification', 'user_auth', 'main', 'Titre principal de la page d''authentification'),
('fr', 'auth.welcome', 'Bienvenue chez Safarine', 'user_auth', 'main', 'Message de bienvenue d''authentification'),
('fr', 'auth.subtitle', 'Connectez-vous pour accéder à votre compte et réservations', 'user_auth', 'main', 'Sous-titre d''authentification'),
('fr', 'auth.email', 'Email', 'user_auth', 'main', 'Libellé du champ email'),
('fr', 'auth.password', 'Mot de passe', 'user_auth', 'main', 'Libellé du champ mot de passe'),
('fr', 'auth.confirmPassword', 'Confirmer le mot de passe', 'user_auth', 'main', 'Libellé de confirmation du mot de passe'),
('fr', 'auth.login.title', 'Se connecter', 'user_auth', 'main', 'Titre de l''onglet connexion'),
('fr', 'auth.login.submit', 'Se connecter', 'user_auth', 'main', 'Bouton de soumission connexion'),
('fr', 'auth.login.success', 'Connexion réussie !', 'user_auth', 'main', 'Message de succès de connexion'),
('fr', 'auth.login.error', 'Email ou mot de passe invalide', 'user_auth', 'main', 'Message d''erreur de connexion'),
('fr', 'auth.register.title', 'S''inscrire', 'user_auth', 'main', 'Titre de l''onglet inscription'),
('fr', 'auth.register.submit', 'Créer un compte', 'user_auth', 'main', 'Bouton de soumission inscription'),
('fr', 'auth.register.success', 'Compte créé ! Veuillez vérifier votre email pour confirmer votre compte.', 'user_auth', 'main', 'Message de succès d''inscription'),
('fr', 'auth.register.error', 'Échec de la création du compte', 'user_auth', 'main', 'Message d''erreur d''inscription'),
('fr', 'auth.register.passwordMismatch', 'Les mots de passe ne correspondent pas', 'user_auth', 'main', 'Erreur de non-correspondance des mots de passe'),
('fr', 'auth.signOut', 'Se déconnecter', 'user_auth', 'main', 'Bouton de déconnexion'),
('fr', 'auth.meta.description', 'Connectez-vous ou créez un compte pour accéder à vos réservations et profil Safarine Tours', 'user_auth', 'main', 'Description meta de la page d''authentification'),
('fr', 'profile.title', 'Mon Profil', 'user_auth', 'main', 'Titre de la page profil'),
('fr', 'profile.memberSince', 'Membre depuis', 'user_auth', 'main', 'Libellé membre depuis'),
('fr', 'profile.meta.description', 'Gérez votre profil et paramètres de compte Safarine Tours', 'user_auth', 'main', 'Description meta de la page profil'),
('fr', 'menu.account', 'Mon Compte', 'user_auth', 'main', 'Élément de menu compte');