-- Phase 2: Add comprehensive translation keys for admin form validation and wizard components

-- Tour Creation Wizard Keys
INSERT INTO translations (key, en, fr) VALUES
-- Wizard Steps
('admin.wizard.steps.basic_info.title', 'Basic Tour Information', 'Informations de Base du Tour'),
('admin.wizard.steps.basic_info.description', 'Enter the essential details for your tour', 'Entrez les détails essentiels de votre tour'),
('admin.wizard.steps.itinerary.title', 'Build Itinerary', 'Construire l''Itinéraire'),
('admin.wizard.steps.itinerary.description', 'Create a detailed day-by-day schedule', 'Créez un programme détaillé jour par jour'),
('admin.wizard.steps.highlights.title', 'Tour Highlights', 'Points Forts du Tour'),
('admin.wizard.steps.highlights.description', 'Add key features and attractions', 'Ajoutez les caractéristiques et attractions clés'),
('admin.wizard.steps.inclusions.title', 'Inclusions & Exclusions', 'Inclusions et Exclusions'),
('admin.wizard.steps.inclusions.description', 'Define what''s included in the package', 'Définissez ce qui est inclus dans le forfait'),
('admin.wizard.steps.images.title', 'Image Management', 'Gestion des Images'),
('admin.wizard.steps.images.description', 'Upload hero and gallery images', 'Téléchargez les images principales et de galerie'),

-- Wizard Navigation
('admin.wizard.navigation.back_to_tours', 'Back to Tours', 'Retour aux Tours'),
('admin.wizard.navigation.save_draft', 'Save Draft', 'Sauvegarder le Brouillon'),
('admin.wizard.navigation.previous', 'Previous', 'Précédent'),
('admin.wizard.navigation.next', 'Next', 'Suivant'),
('admin.wizard.navigation.create_tour', 'Create Tour', 'Créer le Tour'),
('admin.wizard.navigation.step_of', 'Step {current} of {total}', 'Étape {current} sur {total}'),

-- Basic Tour Info Step
('admin.wizard.basic.tour_titles', 'Tour Titles', 'Titres des Tours'),
('admin.wizard.basic.title_english', 'Title (English)', 'Titre (Anglais)'),
('admin.wizard.basic.title_french', 'Title (French)', 'Titre (Français)'),
('admin.wizard.basic.location_duration', 'Location & Duration', 'Lieu et Durée'),
('admin.wizard.basic.destination', 'Destination', 'Destination'),
('admin.wizard.basic.select_destination', 'Select destination', 'Sélectionner la destination'),
('admin.wizard.basic.days', 'Days', 'Jours'),
('admin.wizard.basic.nights', 'Nights', 'Nuits'),
('admin.wizard.basic.pricing', 'Pricing', 'Tarification'),
('admin.wizard.basic.price', 'Price', 'Prix'),
('admin.wizard.basic.currency', 'Currency', 'Devise'),
('admin.wizard.basic.tour_settings', 'Tour Settings', 'Paramètres du Tour'),
('admin.wizard.basic.difficulty_level', 'Difficulty Level', 'Niveau de Difficulté'),
('admin.wizard.basic.min_group_size', 'Min Group Size', 'Taille Min du Groupe'),
('admin.wizard.basic.max_group_size', 'Max Group Size', 'Taille Max du Groupe'),
('admin.wizard.basic.supported_languages', 'Supported Languages', 'Langues Supportées'),
('admin.wizard.basic.descriptions', 'Descriptions', 'Descriptions'),
('admin.wizard.basic.description_english', 'Description (English)', 'Description (Anglais)'),
('admin.wizard.basic.description_french', 'Description (French)', 'Description (Français)'),

-- Itinerary Builder Step
('admin.wizard.itinerary.title', 'Build Your Tour Itinerary', 'Construisez Votre Itinéraire de Tour'),
('admin.wizard.itinerary.description', 'Create a detailed day-by-day schedule for your tour', 'Créez un programme détaillé jour par jour pour votre tour'),
('admin.wizard.itinerary.no_duration', 'Please set the tour duration in the Basic Information step first.', 'Veuillez d''abord définir la durée du tour dans l''étape Informations de Base.'),
('admin.wizard.itinerary.day_title', 'Day {day}', 'Jour {day}'),
('admin.wizard.itinerary.day_title_label', 'Day Title ({language})', 'Titre du Jour ({language})'),
('admin.wizard.itinerary.activities', 'Activities', 'Activités'),
('admin.wizard.itinerary.add_activity', 'Add Activity', 'Ajouter une Activité'),
('admin.wizard.itinerary.time', 'Time', 'Heure'),
('admin.wizard.itinerary.activity_description', 'Activity Description ({language})', 'Description de l''Activité ({language})'),
('admin.wizard.itinerary.no_activities', 'No activities added for this day yet.', 'Aucune activité ajoutée pour ce jour encore.'),
('admin.wizard.itinerary.english', 'English', 'Anglais'),
('admin.wizard.itinerary.french', 'French', 'Français'),

-- Highlights Step
('admin.wizard.highlights.title', 'Tour Highlights', 'Points Forts du Tour'),
('admin.wizard.highlights.description', 'Add the key features and attractions that make your tour special', 'Ajoutez les caractéristiques clés et attractions qui rendent votre tour spécial'),
('admin.wizard.highlights.count', '{count} Highlight', '{count} Point Fort'),
('admin.wizard.highlights.count_plural', '{count} Highlights', '{count} Points Forts'),
('admin.wizard.highlights.add_highlight', 'Add Highlight', 'Ajouter un Point Fort'),
('admin.wizard.highlights.highlight_number', 'Highlight {number}', 'Point Fort {number}'),
('admin.wizard.highlights.title_field', 'Title ({language}) *', 'Titre ({language}) *'),
('admin.wizard.highlights.description_field', 'Description ({language}) *', 'Description ({language}) *'),
('admin.wizard.highlights.no_highlights', 'No highlights added yet. Highlights help showcase what makes your tour unique.', 'Aucun point fort ajouté encore. Les points forts aident à présenter ce qui rend votre tour unique.'),
('admin.wizard.highlights.add_first', 'Add Your First Highlight', 'Ajoutez Votre Premier Point Fort'),
('admin.wizard.highlights.tips_title', 'Tips for Great Highlights:', 'Conseils pour de Bons Points Forts :'),
('admin.wizard.highlights.tip_1', 'Focus on unique experiences and attractions', 'Concentrez-vous sur des expériences et attractions uniques'),
('admin.wizard.highlights.tip_2', 'Use specific details (altitudes, historical facts, etc.)', 'Utilisez des détails spécifiques (altitudes, faits historiques, etc.)'),
('admin.wizard.highlights.tip_3', 'Keep descriptions concise but compelling', 'Gardez les descriptions concises mais convaincantes'),
('admin.wizard.highlights.tip_4', 'Order highlights by importance or chronological flow', 'Ordonnez les points forts par importance ou flux chronologique'),

-- Inclusions Step
('admin.wizard.inclusions.whats_included', 'What''s Included', 'Ce qui est Inclus'),
('admin.wizard.inclusions.whats_excluded', 'What''s Excluded', 'Ce qui est Exclu'),
('admin.wizard.inclusions.common_inclusions', 'Common Inclusions', 'Inclusions Communes'),
('admin.wizard.inclusions.common_exclusions', 'Common Exclusions', 'Exclusions Communes'),
('admin.wizard.inclusions.add_custom', 'Add Custom Item', 'Ajouter un Élément Personnalisé'),
('admin.wizard.inclusions.custom_inclusion', 'Custom inclusion...', 'Inclusion personnalisée...'),
('admin.wizard.inclusions.custom_exclusion', 'Custom exclusion...', 'Exclusion personnalisée...'),
('admin.wizard.inclusions.selected_items', 'Selected Items', 'Éléments Sélectionnés'),
('admin.wizard.inclusions.no_inclusions', 'No inclusions selected yet.', 'Aucune inclusion sélectionnée encore.'),
('admin.wizard.inclusions.no_exclusions', 'No exclusions specified yet.', 'Aucune exclusion spécifiée encore.'),
('admin.wizard.inclusions.tips_title', 'Tips for Clear Inclusions/Exclusions:', 'Conseils pour des Inclusions/Exclusions Claires :'),
('admin.wizard.inclusions.tip_1', 'Be specific about what''s covered vs. not covered', 'Soyez spécifique sur ce qui est couvert vs. non couvert'),
('admin.wizard.inclusions.tip_2', 'Mention meal types, accommodation standards, etc.', 'Mentionnez les types de repas, standards d''hébergement, etc.'),
('admin.wizard.inclusions.tip_3', 'Clarify personal expenses and optional activities', 'Clarifiez les dépenses personnelles et activités optionnelles'),

-- Image Management Step
('admin.wizard.images.title', 'Image Management', 'Gestion des Images'),
('admin.wizard.images.description', 'Upload and manage hero and gallery images for your tour', 'Téléchargez et gérez les images principales et de galerie pour votre tour'),
('admin.wizard.images.hero_image', 'Hero Image', 'Image Principale'),
('admin.wizard.images.gallery_images', 'Gallery Images', 'Images de Galerie'),
('admin.wizard.images.upload_hero', 'Upload Hero Image', 'Télécharger l''Image Principale'),
('admin.wizard.images.upload_gallery', 'Upload Gallery Images', 'Télécharger les Images de Galerie'),
('admin.wizard.images.alt_text', 'Alt Text ({language})', 'Texte Alt ({language})'),
('admin.wizard.images.image_title', 'Image Title ({language})', 'Titre de l''Image ({language})'),
('admin.wizard.images.remove_image', 'Remove Image', 'Supprimer l''Image'),
('admin.wizard.images.no_hero', 'No hero image uploaded yet.', 'Aucune image principale téléchargée encore.'),
('admin.wizard.images.no_gallery', 'No gallery images uploaded yet.', 'Aucune image de galerie téléchargée encore.'),
('admin.wizard.images.guidelines_title', 'Image Guidelines:', 'Directives d''Images :'),
('admin.wizard.images.guideline_1', 'Hero image should be high-resolution (min 1200x800px)', 'L''image principale doit être haute résolution (min 1200x800px)'),
('admin.wizard.images.guideline_2', 'Gallery images should showcase tour highlights', 'Les images de galerie doivent présenter les points forts du tour'),
('admin.wizard.images.guideline_3', 'Use descriptive alt text for accessibility', 'Utilisez un texte alt descriptif pour l''accessibilité'),

-- Validation Error Messages
('validation.errors.required', 'This field is required', 'Ce champ est requis'),
('validation.errors.email.invalid', 'Please enter a valid email address', 'Veuillez entrer une adresse e-mail valide'),
('validation.errors.email.too_long', 'Email address is too long (max 254 characters)', 'L''adresse e-mail est trop longue (max 254 caractères)'),
('validation.errors.password.too_short', 'Password must be at least 8 characters long', 'Le mot de passe doit contenir au moins 8 caractères'),
('validation.errors.password.missing_uppercase', 'Password must contain at least one uppercase letter', 'Le mot de passe doit contenir au moins une lettre majuscule'),
('validation.errors.password.missing_lowercase', 'Password must contain at least one lowercase letter', 'Le mot de passe doit contenir au moins une lettre minuscule'),
('validation.errors.password.missing_number', 'Password must contain at least one number', 'Le mot de passe doit contenir au moins un chiffre'),
('validation.errors.password.missing_special', 'Password must contain at least one special character', 'Le mot de passe doit contenir au moins un caractère spécial'),
('validation.errors.text.too_short', '{field} must be at least {min} characters long', '{field} doit contenir au moins {min} caractères'),
('validation.errors.text.too_long', '{field} must be no more than {max} characters long', '{field} ne doit pas dépasser {max} caractères'),
('validation.errors.text.invalid_chars', '{field} contains invalid characters', '{field} contient des caractères invalides'),
('validation.errors.phone.invalid', 'Please enter a valid phone number', 'Veuillez entrer un numéro de téléphone valide'),

-- Admin Import Messages
('admin.import.csv.title', 'CSV Import', 'Import CSV'),
('admin.import.csv.description', 'Import tour data from CSV files', 'Importer des données de tour depuis des fichiers CSV'),
('admin.import.safarine.title', 'Safarine Import', 'Import Safarine'),
('admin.import.safarine.description', 'Import existing Safarine tour data', 'Importer les données existantes de tour Safarine'),
('admin.import.upload_file', 'Upload File', 'Télécharger le Fichier'),
('admin.import.processing', 'Processing...', 'Traitement en cours...'),
('admin.import.success', 'Import completed successfully', 'Import terminé avec succès'),
('admin.import.error', 'Import failed: {error}', 'Échec de l''import : {error}'),
('admin.import.validation_error', 'Validation error in row {row}: {error}', 'Erreur de validation à la ligne {row} : {error}'),

-- Toast Messages
('admin.messages.tour_created', 'Tour created successfully', 'Tour créé avec succès'),
('admin.messages.tour_updated', 'Tour updated successfully', 'Tour mis à jour avec succès'),
('admin.messages.tour_deleted', 'Tour deleted successfully', 'Tour supprimé avec succès'),
('admin.messages.draft_saved', 'Draft saved successfully', 'Brouillon sauvegardé avec succès'),
('admin.messages.validation_failed', 'Please fix validation errors before proceeding', 'Veuillez corriger les erreurs de validation avant de continuer'),
('admin.messages.upload_failed', 'File upload failed', 'Échec du téléchargement de fichier'),
('admin.messages.upload_success', 'File uploaded successfully', 'Fichier téléchargé avec succès'),

-- Common Form Labels
('admin.forms.labels.title', 'Title', 'Titre'),
('admin.forms.labels.description', 'Description', 'Description'),
('admin.forms.labels.price', 'Price', 'Prix'),
('admin.forms.labels.duration', 'Duration', 'Durée'),
('admin.forms.labels.difficulty', 'Difficulty', 'Difficulté'),
('admin.forms.labels.capacity', 'Capacity', 'Capacité'),
('admin.forms.labels.location', 'Location', 'Lieu'),
('admin.forms.labels.category', 'Category', 'Catégorie'),
('admin.forms.labels.status', 'Status', 'Statut'),

-- Difficulty Levels
('admin.difficulty.easy', 'Easy', 'Facile'),
('admin.difficulty.moderate', 'Moderate', 'Modéré'),
('admin.difficulty.challenging', 'Challenging', 'Difficile'),
('admin.difficulty.extreme', 'Extreme', 'Extrême'),

-- Languages
('admin.languages.english', 'English', 'Anglais'),
('admin.languages.french', 'French', 'Français'),
('admin.languages.thai', 'Thai', 'Thaï'),
('admin.languages.spanish', 'Spanish', 'Espagnol'),
('admin.languages.german', 'German', 'Allemand'),
('admin.languages.italian', 'Italian', 'Italien'),
('admin.languages.chinese', 'Chinese', 'Chinois'),
('admin.languages.japanese', 'Japanese', 'Japonais');