-- Insert additional missing B2B translation keys
INSERT INTO public.translations (key_name, locale, value, category, namespace) VALUES

-- B2B Tours Table translations
('b2b.table.searchPlaceholder', 'en', 'Search tours...', 'b2b', 'dashboard'),
('b2b.table.searchPlaceholder', 'fr', 'Rechercher des circuits...', 'b2b', 'dashboard'),
('b2b.table.filter', 'en', 'Filter', 'b2b', 'dashboard'),
('b2b.table.filter', 'fr', 'Filtrer', 'b2b', 'dashboard'),
('b2b.table.exportSelected', 'en', 'Export Selected', 'b2b', 'dashboard'),
('b2b.table.exportSelected', 'fr', 'Exporter la Sélection', 'b2b', 'dashboard'),
('b2b.table.selectAll', 'en', 'Select all', 'b2b', 'dashboard'),
('b2b.table.selectAll', 'fr', 'Sélectionner tout', 'b2b', 'dashboard'),
('b2b.table.deselectAll', 'en', 'Deselect all', 'b2b', 'dashboard'),
('b2b.table.deselectAll', 'fr', 'Désélectionner tout', 'b2b', 'dashboard'),
('b2b.table.tourName', 'en', 'Tour Name', 'b2b', 'dashboard'),
('b2b.table.tourName', 'fr', 'Nom du Circuit', 'b2b', 'dashboard'),
('b2b.table.duration', 'en', 'Duration', 'b2b', 'dashboard'),
('b2b.table.duration', 'fr', 'Durée', 'b2b', 'dashboard'),
('b2b.table.destination', 'en', 'Destination', 'b2b', 'dashboard'),
('b2b.table.destination', 'fr', 'Destination', 'b2b', 'dashboard'),
('b2b.table.retailPrice', 'en', 'Retail Price', 'b2b', 'dashboard'),
('b2b.table.retailPrice', 'fr', 'Prix Public', 'b2b', 'dashboard'),
('b2b.table.b2bRate', 'en', 'B2B Rate', 'b2b', 'dashboard'),
('b2b.table.b2bRate', 'fr', 'Tarif B2B', 'b2b', 'dashboard'),
('b2b.table.details', 'en', 'Details', 'b2b', 'dashboard'),
('b2b.table.details', 'fr', 'Détails', 'b2b', 'dashboard'),
('b2b.table.viewDetails', 'en', 'View Details', 'b2b', 'dashboard'),
('b2b.table.viewDetails', 'fr', 'Voir Détails', 'b2b', 'dashboard'),
('b2b.table.day', 'en', 'day', 'b2b', 'dashboard'),
('b2b.table.day', 'fr', 'jour', 'b2b', 'dashboard'),
('b2b.table.days', 'en', 'days', 'b2b', 'dashboard'),
('b2b.table.days', 'fr', 'jours', 'b2b', 'dashboard'),
('b2b.table.selected', 'en', 'selected', 'b2b', 'dashboard'),
('b2b.table.selected', 'fr', 'sélectionné(s)', 'b2b', 'dashboard'),
('b2b.table.tours', 'en', 'tours', 'b2b', 'dashboard'),
('b2b.table.tours', 'fr', 'circuits', 'b2b', 'dashboard'),
('b2b.table.loading', 'en', 'Loading tours...', 'b2b', 'dashboard'),
('b2b.table.loading', 'fr', 'Chargement des circuits...', 'b2b', 'dashboard'),
('b2b.table.noTours', 'en', 'No tours found', 'b2b', 'dashboard'),
('b2b.table.noTours', 'fr', 'Aucun circuit trouvé', 'b2b', 'dashboard'),
('b2b.table.sortBy', 'en', 'Sort by', 'b2b', 'dashboard'),
('b2b.table.sortBy', 'fr', 'Trier par', 'b2b', 'dashboard'),

-- B2B Export translations  
('b2b.export.success', 'en', 'CSV exported successfully', 'b2b', 'dashboard'),
('b2b.export.success', 'fr', 'CSV exporté avec succès', 'b2b', 'dashboard'),
('b2b.export.error', 'en', 'CSV export failed', 'b2b', 'dashboard'),
('b2b.export.error', 'fr', 'Erreur lors de l''export CSV', 'b2b', 'dashboard'),
('b2b.export.filename', 'en', 'safarine-tours-b2b', 'b2b', 'dashboard'),
('b2b.export.filename', 'fr', 'circuits-safarine-b2b', 'b2b', 'dashboard'),
('b2b.export.selectTours', 'en', 'Please select tours to export', 'b2b', 'dashboard'),
('b2b.export.selectTours', 'fr', 'Veuillez sélectionner des circuits à exporter', 'b2b', 'dashboard'),

-- B2B Navigation and User Interface
('b2b.nav.dashboard', 'en', 'Dashboard', 'b2b', 'navigation'),
('b2b.nav.dashboard', 'fr', 'Tableau de Bord', 'b2b', 'navigation'),
('b2b.nav.tours', 'en', 'Tours', 'b2b', 'navigation'),
('b2b.nav.tours', 'fr', 'Circuits', 'b2b', 'navigation'),
('b2b.nav.favorites', 'en', 'Favorites', 'b2b', 'navigation'),
('b2b.nav.favorites', 'fr', 'Favoris', 'b2b', 'navigation'),
('b2b.nav.downloads', 'en', 'Downloads', 'b2b', 'navigation'),
('b2b.nav.downloads', 'fr', 'Téléchargements', 'b2b', 'navigation'),
('b2b.nav.settings', 'en', 'Settings', 'b2b', 'navigation'),
('b2b.nav.settings', 'fr', 'Paramètres', 'b2b', 'navigation'),
('b2b.nav.logout', 'en', 'Logout', 'b2b', 'navigation'),
('b2b.nav.logout', 'fr', 'Déconnexion', 'b2b', 'navigation'),

-- B2B Header
('b2b.header.welcome', 'en', 'Welcome back', 'b2b', 'header'),
('b2b.header.welcome', 'fr', 'Bon retour', 'b2b', 'header'),
('b2b.header.language', 'en', 'Language', 'b2b', 'header'),
('b2b.header.language', 'fr', 'Langue', 'b2b', 'header'),
('b2b.header.settings', 'en', 'Settings', 'b2b', 'header'),
('b2b.header.settings', 'fr', 'Paramètres', 'b2b', 'header'),
('b2b.header.logout', 'en', 'Logout', 'b2b', 'header'),
('b2b.header.logout', 'fr', 'Déconnexion', 'b2b', 'header'),

-- B2B Dashboard page metadata
('b2b.dashboard.pageTitle', 'en', 'B2B Dashboard - Safarine Tours', 'b2b', 'meta'),
('b2b.dashboard.pageTitle', 'fr', 'Tableau de Bord Professionnel - Safarine Tours', 'b2b', 'meta'),
('b2b.dashboard.pageDescription', 'en', 'Manage your tours and account', 'b2b', 'meta'),
('b2b.dashboard.pageDescription', 'fr', 'Gérez vos circuits et votre compte', 'b2b', 'meta'),
('b2b.dashboard.welcome', 'en', 'Welcome back, {name}', 'b2b', 'dashboard'),
('b2b.dashboard.welcome', 'fr', 'Bienvenue, {name}', 'b2b', 'dashboard'),
('b2b.dashboard.subtitle', 'en', 'Managing {company}', 'b2b', 'dashboard'),
('b2b.dashboard.subtitle', 'fr', 'Gestion de {company}', 'b2b', 'dashboard'),
('b2b.dashboard.recentActivity', 'en', 'Recent Activity', 'b2b', 'dashboard'),
('b2b.dashboard.recentActivity', 'fr', 'Activité Récente', 'b2b', 'dashboard'),
('b2b.dashboard.activityDescription', 'en', 'Latest updates in your dashboard', 'b2b', 'dashboard'),
('b2b.dashboard.activityDescription', 'fr', 'Dernières mises à jour dans votre tableau de bord', 'b2b', 'dashboard'),

-- B2B Settings
('b2b.settings.title', 'en', 'Account Settings', 'b2b', 'settings'),
('b2b.settings.title', 'fr', 'Paramètres du Compte', 'b2b', 'settings'),
('b2b.settings.company', 'en', 'Company', 'b2b', 'settings'),
('b2b.settings.company', 'fr', 'Entreprise', 'b2b', 'settings'),
('b2b.settings.contact', 'en', 'Contact Person', 'b2b', 'settings'),
('b2b.settings.contact', 'fr', 'Personne de Contact', 'b2b', 'settings'),
('b2b.settings.email', 'en', 'Email', 'b2b', 'settings'),
('b2b.settings.email', 'fr', 'Email', 'b2b', 'settings'),
('b2b.settings.phone', 'en', 'Phone', 'b2b', 'settings'),
('b2b.settings.phone', 'fr', 'Téléphone', 'b2b', 'settings'),
('b2b.settings.commission', 'en', 'Commission Rate', 'b2b', 'settings'),
('b2b.settings.commission', 'fr', 'Taux de Commission', 'b2b', 'settings'),
('b2b.settings.editProfile', 'en', 'Edit Profile', 'b2b', 'settings'),
('b2b.settings.editProfile', 'fr', 'Modifier le Profil', 'b2b', 'settings'),
('b2b.settings.changePassword', 'en', 'Change Password', 'b2b', 'settings'),
('b2b.settings.changePassword', 'fr', 'Changer le Mot de Passe', 'b2b', 'settings')

ON CONFLICT (key_name, locale, namespace) DO NOTHING;