// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcnzcagvdcoutqdfceai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jbnpjYWd2ZGNvdXRxZGZjZWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzEwOTAsImV4cCI6MjA2MzUwNzA5MH0.TvYk90UiGXaJh2Pr9lqlnL-904A8Ke6jZnjPds3AwEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Default anonymous client for public operations
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Function to create an authenticated client with JWT token
export const createAuthenticatedClient = (token: string): SupabaseClient<Database> => {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    },
  });
};

// Function to update the global client with authentication
let authenticatedClient: SupabaseClient<Database> | null = null;

export const setSupabaseAuth = async (token: string) => {
  try {
    authenticatedClient = createAuthenticatedClient(token);
    
    // Set the session on the authenticated client
    const { error } = await authenticatedClient.auth.setSession({
      access_token: token,
      refresh_token: token,
    });
    
    if (error) {
      console.error('Error setting Supabase session:', error);
      return false;
    }
    
    console.log('✅ Supabase authenticated client updated');
    return true;
  } catch (error) {
    console.error('Error setting Supabase auth:', error);
    return false;
  }
};

// Get the authenticated client or fall back to anonymous
export const getSupabaseClient = (): SupabaseClient<Database> => {
  return authenticatedClient || supabase;
};